services:
  - type: web
    name: lodge-booking-frontend
    buildCommand: cd lodge-booking-frontend && npm install && npm run build
    staticPublishPath: lodge-booking-frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 20
